# Generated by Django 4.2.7 on 2026-01-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destination_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
