# Generated by Django 4.2.7 on 2026-02-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_itineraryday_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryday',
            name='title',
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
