# Generated by Django 4.2.7 on 2026-04-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
